language: python

python:
  - "3.8"

install:
  - "pip install --upgrade pip"
  - "pip install --upgrade setuptools"
  - "pip install -r requirements.txt"
  - "pip install -r dev-requirements.txt"

addons:
  postgresql: "9.6"

before_script:
  - psql -c 'create database test;' -U postgres

script:
  - "py.test"

after_success:
  - "coveralls"

notifications:
  email: false

sudo: false
