language: python

python:
  - "2.7"

install:
  - "pip install --upgrade pip"
  - "pip install --upgrade setuptools"
  - "pip install -r requirements.txt"
  - "pip install -r dev-requirements.txt"

before script:
  - "psql -h localhost --port 15432 -U postgres testdb"

script:
  - "py.test"

after_success:
  - "coveralls"

notifications:
  email: false

sudo: false

addons:
  postgresql: "9.6"