language: python

python:
  - "2.7"

install:
  - "pip install --upgrade pip"
  - "pip install --upgrade setuptools"
  - "pip install -r requirements.txt"
  - "pip install -r dev-requirements.txt"

services:
  - postgresql

before script:
  - psql -c 'create database testdb;' -U postgres
  - psql -c "CREATE USER root WITH PASSWORD 'postgres';" -U postgres

script:
  - "py.test"

after_success:
  - "coveralls"

notifications:
  email: false

sudo: false

addons:
  postgresql: "9.6"