"""created db 2.0 structure

Revision ID: ae6ce5939484
Revises: d5c302c1b4a2
Create Date: 2021-08-19 15:02:57.463119

"""

# revision identifiers, used by Alembic.
revision = 'ae6ce5939484'
down_revision = 'd5c302c1b4a2'

from alembic import op
import sqlalchemy as sa


from sqlalchemy.dialects import postgresql

def upgrade():
    #with app.app_context() as c:
    #   db.session.add(Model())
    #   db.session.commit()

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('bibcode', sa.String(), nullable=False),
    sa.Column('identifier', postgresql.ARRAY(sa.String()), nullable=False, index=True),
    sa.Column('links', postgresql.JSONB(), nullable=False),
    sa.PrimaryKeyConstraint('bibcode')
    )
    op.create_index(op.f('identifier_index'), 'documents', [sa.text('identifier')], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    # ### end Alembic commands ###
