"""created db structure

Revision ID: d5c302c1b4a2
Revises: None
Create Date: 2018-01-01 14:47:26.219044

"""

# revision identifiers, used by Alembic.
revision = 'd5c302c1b4a2'
down_revision = None

from alembic import op
import sqlalchemy as sa


from sqlalchemy.dialects import postgresql

def upgrade():
    #with app.app_context() as c:
    #   db.session.add(Model())
    #   db.session.commit()

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datalinks',
    sa.Column('bibcode', sa.String(), nullable=False),
    sa.Column('link_type', sa.String(), nullable=False),
    sa.Column('link_sub_type', sa.String(), nullable=False),
    sa.Column('url', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('title', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('bibcode', 'link_type', 'link_sub_type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datalinks')
    # ### end Alembic commands ###